### ISSUE TITLE
Add meta tags for smart app banners

### ISSUE THREAD

**Issue by rodericj** [jamescmartinez/coffeecoffeecoffee.coffee#2]
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

Probably dependent upon https://github.com/gravicle/sf-ios getting into the App Store.

**Comment by jamescmartinez** [comment]
Going to close since he's now an Apple Employee (tm)
