### ISSUE TITLE
Add support for another calendar

### ISSUE THREAD

**Issue by brennanMKE** [jamescmartinez/coffeecoffeecoffee.coffee#7]
In addition to the coffee meetup the page could also include details for the beer meetup which is on Thursdays. But perhaps with variables being defined to use at runtime then a 2nd Heroku app could be deployed with the variables set for another calendar.

https://github.com/jamescmartinez/beverage/issues/6

**Comment by jamescmartinez** [comment]
Now that I finished the rewrite, `groups` are coming.

**Comment by jamescmartinez** [comment]
BOOM, DONE. 💣 

Coffee: http://coffeecoffeecoffee.coffee/groups/28ef50f9-b909-4f03-9a69-a8218a8cbd99/next_event

Beer: http://coffeecoffeecoffee.coffee/groups/62e7a8ae-b552-4721-b273-62021872acf1/next_event

I'll make the URLs prettier later.
